# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_task_tasklogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceurl',
            name='web_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Web URL地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
