# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='login_ip',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作IP'),
        ),
    ]
